# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: SS-Azure-CICD-001-VM #SS-Agent-Pool-001
  #vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: UiPathInstallPlatform@3
  inputs:
    cliVersion: 'WIN_22.10.8438.32859'
    cliNupkgPath: 'UiPath.CLI.Windows.22.10.8438.32859.nupkg'

- task: UiPathPack@3
  inputs:
    versionType: 'CurrentVersion'
    projectJsonPath: '$(Build.SourcesDirectory)\project.json'
    #outputType: 'Process'
    orchestratorConnection: 'SS-ServiceConnection-001'
    outputPath: '$(Build.ArtifactStagingDirectory)\Output'

- task: UiPathDeploy@3
  inputs:
    orchestratorConnection: 'SS-ServiceConnection-001'
    packagesPath: '$(Build.ArtifactStagingDirectory)\Output'
    folderName: 'Shared'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
